### ISSUE TITLE
node has multiple entries after re-flashing

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/mesh-monitor#3]
Is it possible to base entries on MAC addresses? Everything else can change after flashing.

<img width="312" alt="screen shot 2016-01-02 at 6 38 15 pm" src="https://cloud.githubusercontent.com/assets/1037006/12076608/42f486ba-b180-11e5-875a-47fa09638a33.png">

**Comment by xtream1101** [comment]
Using the mac address would be ideal, just need to find a command that will give that info.

The command that is currently being used is `bmx6 -c --originators`. If we can find another that will get the node list and the mac's in one command that would be best. If not we will have to run a command on each ipv6 to find the mac.
